### ISSUE TITLE
```YAML codeblock not closing correctly

### ISSUE THREAD

**Issue by nrser** [atom/language-gfm#195]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

YAML code block not closing correctly:

![screen shot 2017-04-06 at 2 38 14 pm](https://cloud.githubusercontent.com/assets/207603/24741313/f50157fe-1ad7-11e7-97f6-a2b0d8fee31c.png)

as you can see, the YAML syntax highlighting extends beyond the fence close.

code in question (though i'm pretty sure i've seen it other places as well):

https://gist.github.com/nrser/6078765f46d8ee8e4b89f88f9caa69ef

### Steps to Reproduce

1. put that code in the editor.

**Expected behavior:** YAML highlighting stops at closing tripple-backtick

**Actual behavior:** YAML highlighting continues to end of document.

**Reproduces how often:** seems consistent.

### Versions

```
$ atom --version
Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.12
git 2.8.2
```

on macOS 10.12.3.

**Comment by nrser** [comment]
take away the "YAML" and it works fine:

![screen shot 2017-04-06 at 2 54 30 pm](https://cloud.githubusercontent.com/assets/207603/24741560/09ad3a3c-1ad9-11e7-9afa-8f19800bb6e3.png)

**Comment by 50Wliu** [comment]
This should be fixed in either Atom 1.15.0, which is already out, or Atom 1.16.0, which should be out in the coming weeks.

**Comment by nrser** [comment]
my editor says 1.15.0, not sure why `atom --version` said 1.14.3. still seeing it in that version. look forward to 1.16, thanks.
